{% set name = "icepapcms" %}
{% set version = "3.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icepapcms-{{ version }}.tar.gz
  sha256: d6386eda31ef12389c71dd391b1ff688ba5a4eb988404d5f0d19f313febbdc5c

build:
  number: 0
  noarch: python
  entry_points:
    - icepapcms = icepapcms.__main__:main
    - ipapconsole = icepapcms.gui.ipapconsole:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - configobj
    - icepap >=3.6.1
    - ipy >=0.62
    - ldap3
    - pyqt >=5.12.3
    - python >=3.5
    - pyyaml
    - storm >=0.23

test:
  imports:
    - icepapcms
    - icepapcms.gui
    - icepapcms.gui.icepapcms
    - icepapcms.gui.ipapconsole
    - icepapcms.lib
  commands:
    - pip check
    - icepapcms --help
  requires:
    - pip

about:
  home: https://github.com/ALBA-Synchrotron/IcepapCMS
  summary: Icepap Configuration Management System and Test Tool
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - beenje
    - perhedmax
